// Replace every YOUR_* value before use. This file is an example only.
using './mcp-aca-main.bicep'

param location = 'westus3'
param vnetName = 'vnet-ai-access'
param acaSubnetName = 'snet-mcp-aca'
param acaSubnetAddressPrefix = '10.50.2.0/27'
param managedEnvironmentName = 'cae-mcp-private'
param logAnalyticsWorkspaceName = 'log-litellm-4bqvj62ztmxmi'
param acrName = 'cr4bqvj62ztmxmi'
param keyVaultName = 'YOUR_KEY_VAULT_NAME'
param registryHostname = 'registry.example.com'
param keycloakHostname = 'login.example.com'
param registryImage = 'YOUR_ACR_LOGIN_SERVER/registry@sha256:YOUR_REGISTRY_DIGEST'
param authServerImage = 'YOUR_ACR_LOGIN_SERVER/auth-server@sha256:YOUR_AUTH_SERVER_DIGEST'
param mcpgwImage = 'YOUR_ACR_LOGIN_SERVER/mcpgw@sha256:YOUR_MCPGW_DIGEST'
param keycloakImage = 'YOUR_ACR_LOGIN_SERVER/keycloak@sha256:YOUR_KEYCLOAK_DIGEST'
param cloudflaredImage = 'YOUR_ACR_LOGIN_SERVER/cloudflared@sha256:YOUR_CLOUDFLARED_DIGEST'
param keycloakDbHost = 'YOUR_POSTGRES_HOST'
