---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu2404
    image: ubuntu:24.04
    pre_build_image: true
    privileged: false
    command: /usr/bin/tail -f /dev/null
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: ansible
